/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'calculate' : IDL.Func([IDL.Text], [IDL.Float64], []),
  'clear' : IDL.Func([], [], []),
  'getResult' : IDL.Func([], [IDL.Float64], ['query']),
  'inputNumber' : IDL.Func([IDL.Float64], [IDL.Float64], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'calculate' : IDL.Func([IDL.Text], [IDL.Float64], []),
    'clear' : IDL.Func([], [], []),
    'getResult' : IDL.Func([], [IDL.Float64], ['query']),
    'inputNumber' : IDL.Func([IDL.Float64], [IDL.Float64], []),
  });
};

export const init = ({ IDL }) => { return []; };